<a href="https://colab.research.google.com/github/arnav39/AQI-ICG-2022-/blob/main/PyTorch_Tutorial/Tut_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Softmax and Cross entropy loss

In [1]:
import torch 
import torch.nn as nn
import numpy as np

In [3]:
x = torch.ones(5, 4)
print(x)
print(x.sum(axis=0))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([5., 5., 5., 5.])


In [4]:
def softmax(x):
  return np.exp(x) / np.sum(np.exp(x), axis=0)

In [7]:
x = np.array([2., 1., 0.1])
outputs = softmax(x)
print(outputs)

[0.65900114 0.24243297 0.09856589]


In [14]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim=0) # compute along first axis
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [15]:
def cross_entropy(actual, predicted):
  loss = -np.sum(actual * np.log(predicted))
  return loss # can divide by number of samples

In [18]:
y = np.array([1, 0, 0])
y_pred_good = np.array([0.7, 0.2, 0.1])
y_pred_bad = np.array([0.1, 0.6, 0.3])

l1 = cross_entropy(y, y_pred_good)
l2 = cross_entropy(y, y_pred_bad)
print(f"l1 = {l1:.4f}")
print(f"l2 = {l2:.4f}")

l1 = 0.3567
l2 = 2.3026


In [19]:
nn.LogSoftmax??

In [20]:
nn.NLLLoss??

In [21]:
# y : should have class labels not one_hot encoding
# y_pred :  should have raw scores/logits not probability
loss = nn.CrossEntropyLoss()

In [24]:
y = torch.tensor([0])
y_pred_good = torch.tensor([[2.0, 1.0, 0.1]]) # size must be n_samples x n_classes
y_pred_bad = torch.tensor([[0.5, 0.9, 0.3]])

l1 = loss(y_pred_good, y)
l2 = loss(y_pred_bad, y)
print(f"l1 = {l1:.4f}")
print(f"l2 = {l2:.4f}")

l1 = 0.4170
l2 = 1.1971


In [25]:
torch.max??

In [27]:
a = torch.randn(1, 3)
b, c = torch.max(a, 1)
print("b = ", b)
print("c = ", c) # we just need the index not the value

b =  tensor([1.1752])
c =  tensor([0])


In [28]:
_, predictions1 = torch.max(y_pred_good, 1)
_, predictions2 = torch.max(y_pred_bad, 1)

print(predictions1)
print(predictions2)

tensor([0])
tensor([1])


In [30]:
y = torch.tensor([2, 0, 1])
y_pred_good = torch.tensor([[0.1, 1.0, 2.1], [2.4, 0.5, 0.3], [1.3, 5.6, 2.1]])
y_pred_bad = torch.tensor([[0.9, 0.1, 0.2], [1., 2., 3.], [5., 7., 9.]])

_, predictions1 = torch.max(y_pred_good, 1)
_, predictions2 = torch.max(y_pred_bad, 1)

print(predictions1)
print(predictions2)

tensor([2, 0, 1])
tensor([0, 2, 2])


### Multi-class problem

In [31]:
class NeuralNet2(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super().__init__()
    self.linear1 = nn.Linear(input_size, hidden_size) 
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(hidden_size, num_classes)

  def forward(self, X):
    out = self.linear1(X)
    out = self.relu(out)
    out = self.linear2(out)
    return out

In [ ]:
model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss()

for binary classification we use sigmoid activation function and use BCELoss function

In [40]:
class NeuralNet1(nn.Module):
  def __init__(self, input_size, hidden_size):
    super().__init__()
    self.linear1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(hidden_size, 1)

  def forward(self, X):
    out = self.linear1(X)
    out = self.relu(out)
    out = self.linear2(out)
    y_pred = torch.sigmoid(out)
    return y_pred

In [41]:
model = NeuralNet1(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()

# Activation Functions

they apply a non-linear transformation to our layer output

In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

In [4]:
class NeuralNet(nn.Module):

  def __init__(self, input_size, hidden_size):
    super().__init__()
    self.linear1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(hidden_size, 1) 
    self.sigmoid = nn.Sigmoid()

  def forward(self, X):
    out = self.linear1(X)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

  def forward2(self, X): # use activation functions directly in forward pass
    out = torch.ReLU(self.linear1(X))
    out = torch.sigmoid(self.linear2(out))
    return out

In [ ]:
nn.Sigmoid 
nn.ReLU
nn.LeakyReLU
nn.Tanh
nn.Softmax

In [ ]:
F.leaky_relu()